### ISSUE TITLE
Compiled lib throws LNK2019 error

### ISSUE THREAD

**Issue by unuaunco** [progmboy/openprocmon#2]
Hi!
Trying to use precompiled sdk library, but each time it throws error on using of `Drvload.Init(TEXT("PROCMON24"), TEXT("procmon.sys"))`

Errors are:
```[build] test.obj : error LNK2019: unresolved external symbol "public: int __cdecl CDrvLoader::Init(class ATL::CStringT<char,class ATL::StrTraitATL<char,class ATL::ChTraitsCRT<char> > > const &,class ATL::CStringT<char,class ATL::StrTraitATL<char,class ATL::ChTraitsCRT<char> > > const &)" (?Init@CDrvLoader@@QEAAHAEBV?$CStringT@DV?$StrTraitATL@DV?$ChTraitsCRT@D@ATL@@@ATL@@@ATL@@0@Z) referenced in function main [D:\code\testsdk\build\apps\agent.vcxproj]
[build] test.obj : error LNK2019: unresolved external symbol "int __cdecl LogMessage(enum LEVEL,char const *,...)" (?LogMessage@@YAHW4LEVEL@@PEBDZZ) referenced in function "public: virtual int __cdecl CMyEvent::DoEvent(class CRefPtr<class CEventView>)" (?DoEvent@CMyEvent@@UEAAHV?$CRefPtr@VCEventView@@@@@Z) [D:\code\testsdk\build\apps\agent.vcxproj]
[build]     Hint on symbols that are defined and could potentially match:
[build]       "int __cdecl LogMessage(enum LEVEL,wchar_t const *,...)" (?LogMessage@@YAHW4LEVEL@@PEB_WZZ)
[build] test.obj : error LNK2019: unresolved external symbol "public: class ATL::CStringT<char,class ATL::StrTraitATL<char,class ATL::ChTraitsCRT<char> > > __cdecl CEventView::GetPath(void)" (?GetPath@CEventView@@QEAA?AV?$CStringT@DV?$StrTraitATL@DV?$ChTraitsCRT@D@ATL@@@ATL@@@ATL@@XZ) referenced in function "public: virtual int __cdecl CMyEvent::DoEvent(class CRefPtr<class CEventView>)" (?DoEvent@CMyEvent@@UEAAHV?$CRefPtr@VCEventView@@@@@Z) [D:\code\testsdk\build\apps\agent.vcxproj]
[build] test.obj : error LNK2019: unresolved external symbol "public: class ATL::CStringT<char,class ATL::StrTraitATL<char,class ATL::ChTraitsCRT<char> > > __cdecl CEventView::GetProcessName(void)" (?GetProcessName@CEventView@@QEAA?AV?$CStringT@DV?$StrTraitATL@DV?$ChTraitsCRT@D@ATL@@@ATL@@@ATL@@XZ) referenced in function "public: virtual int __cdecl CMyEvent::DoEvent(class CRefPtr<class CEventView>)" (?DoEvent@CMyEvent@@UEAAHV?$CRefPtr@VCEventView@@@@@Z) [D:\code\testsdk\build\apps\agent.vcxproj]
[build] D:\code\testsdk\build\apps\Release\test.exe : fatal error LNK1120: 4 unresolved externals [D:\code\testsdk\build\apps\agent.vcxproj]
[build] Build finished with exit code 1
```

Code I'm trying to build:

```
...
#include <libprocmon/sdk.hpp>
#include <atlstr.h>
#include <atltime.h>

int main(int argc, char *argv[])
{
    CEventMgr &Optmgr = Singleton<CEventMgr>::getInstance();
    CMonitorContoller &Monitormgr = Singleton<CMonitorContoller>::getInstance();
    CDrvLoader &Drvload = Singleton<CDrvLoader>::getInstance();

   //error is on this step
    if (!Drvload.Init(TEXT("PROCMON24"), TEXT("procmon.sys")))
    {
        return -1;
    }
    Optmgr.RegisterCallback(new CMyEvent);
        ...
}
```

CMakeLists looks like this:
```
add_executable(test test.cpp)

# libprocmon link
set(PROCMON_INCLUDE_DIR ${HoneyCornAgent_SOURCE_DIR}/include/libprocmon/)
set(PROCMON_LIBRARY ${HoneyCornAgent_SOURCE_DIR}/src/libprocmon/libprocmon.lib )

include_directories(${PROCMON_INCLUDE_DIR})
include_directories(${HoneyCornAgent_SOURCE_DIR}/src/libprocmon)
include_directories(${HoneyCornAgent_SOURCE_DIR}/lib/procmonsdk/)
include_directories(${HoneyCornAgent_SOURCE_DIR}/lib/procmonsdk/kernel)
include_directories(${HoneyCornAgent_SOURCE_DIR}/lib/procmonsdk/WTL10_10320/Include)
link_directories(${HoneyCornAgent_SOURCE_DIR}/lib/procmonsdk/)
link_directories(${HoneyCornAgent_SOURCE_DIR}/lib/procmonsdk/kernel)
link_directories(${HoneyCornAgent_SOURCE_DIR}/lib/procmonsdk/WTL10_10320/Include)
link_directories(${HoneyCornAgent_SOURCE_DIR}/src/libprocmon)
link_directories({PROCMON_INCLUDE_DIR})

add_library(libprocmon STATIC IMPORTED)
set_target_properties(libprocmon PROPERTIES
  IMPORTED_LOCATION ${PROCMON_LIBRARY}
  INTERFACE_INCLUDE_DIRECTORIES ${PROCMON_INCLUDE_DIR}
)

 target_link_libraries(agent PRIVATE wsock32 ws2_32 atls crypt32 normaliz wldap32 kernel32 user32 gdi32 winspool comdlg32 advapi32 shell32 ole32 oleaut32 uuid odbc32 odbccp32 libprocmon)

```

Library was build using visualstudio as per instruction. The code I'm trying to use based on testsdk.cpp

Am I missing something or it's library building issue?

**Comment by k0keoyo** [comment]
Did you try to use "#pragma comment(lib, "xxx.lib")" in your code?

**Comment by unuaunco** [comment]
> Did you try to use "#pragma comment(lib, "xxx.lib")" in your code?

No, I didn't, cause I'm linking library through cmake lists. But I'll try, thanks

**Comment by progmboy** [comment]
> > Did you try to use "#pragma comment(lib, "xxx.lib")" in your code?
> 
> No, I didn't, cause I'm linking library through cmake lists. But I'll try, thanks

Hi, I update the sdk example with cmake support. You can take a look.

**Comment by unuaunco** [comment]
> 
> 
> > > Did you try to use "#pragma comment(lib, "xxx.lib")" in your code?
> > 
> > 
> > No, I didn't, cause I'm linking library through cmake lists. But I'll try, thanks
> 
> Hi, I update the sdk example with cmake support. You can take a look.

Thank you, @progmboy 
Yes, it works this way. Compiled `example.exe` works good.

Can't catch only one thing - then I copy compiled library (libprocmon.lib) to use in another project, I get LNK2019 errors. Even if I put headers and point `#include sdk.hpp` (`#include <libprocmon/sdk.hpp>` in my case) .

Error like this:
    
    error LNK2019: unresolved external symbol "public: int __cdecl CDrvLoader::Init(class ATL::CStringT<char,class ATL::StrTraitATL<char,class ATL::ChTraitsCRT<char> > > const &,class ATL::CStringT<char,class ATL::StrTraitATL<char,class ATL::ChTraitsCRT<char> > > const &)" (?Init@CDrvLoader@@QEAAHAEBV?$CStringT@DV?$StrTraitATL@DV?$ChTraitsCRT@D@ATL@@@ATL@@@ATL@@0@Z) referenced in function main [D:\code\test\honeycorn-agent\build\apps\agent.vcxproj]

Throws on:

    if(!Drvload.Init(TEXT("PROCMON24"), TEXT("procmon.sys"))){
		return -1;
     }

Lib was connected like this:

    # libprocmon link
    set(PROCMON_INCLUDE_DIR ${HoneyCornAgent_SOURCE_DIR}/include/libprocmon/)
    set(PROCMON_LIBRARY ${HoneyCornAgent_SOURCE_DIR}/src/libprocmon/libprocmon.lib )
    
    include_directories(${PROCMON_INCLUDE_DIR})
    
    add_library(libprocmon STATIC IMPORTED)
    set_target_properties(libprocmon PROPERTIES
      IMPORTED_LOCATION ${PROCMON_LIBRARY}
      INTERFACE_INCLUDE_DIRECTORIES ${PROCMON_INCLUDE_DIR}
    )
    
    if(WIN32)
      set_target_properties(agent PROPERTIES LINK_FLAGS "/MANIFESTUAC:\"level='requireAdministrator' uiAccess='false'\" /NODEFAULTLIB:libcurl")
      target_link_libraries(agent PRIVATE wsock32 ws2_32 atls crypt32 normaliz wldap32 kernel32 user32 gdi32 winspool comdlg32 advapi32 shell32 ole32 oleaut32 uuid odbc32 odbccp32 hpfeeds getopt libcurl libprocmon simpleini json win_service)
    else()
      target_link_libraries(agent PRIVATE hpfeeds getopt)
    endif()




> 
> 
> Did you try to use "#pragma comment(lib, "xxx.lib")" in your code?

Not working as well

**Comment by progmboy** [comment]
> Can't catch only one thing 

**Before running example.exe you need to ensure you are run as administrator.**

Two ways to make the example work.

## Run example.exe with original procmon's driver.

In this way you need
1. Export the procmon's driver from resource which named "RCDRIVERNT" of procmon.exe.
or If you have run procmon before. You can find this driver in "C:\Windows\system32\drivers\PROCMON24.SYS" 
2. Copy `PROCMON24.SYS` to the same directory of `example.exe`. 
3. Rename `PROCMON24.SYS` to `procmon.sys`
4. run example.exe

## Run example.exe with openprocmon's driver.
1. Build the driver from this project. If success `procmon.sys` will be generated.
2. Sign `procmon.sys` with Microsoft Test Signature. In this project we do not support this in cmake. But Original VS project is support this. And you can see :
[How to sign driver with cmake](https://github.com/SergiusTheBest/FindWDK/issues/7)
3. run example.exe

> then I copy compiled library (libprocmon.lib) to use in another project, I get LNK2019 errors. Even if I put headers and point #include sdk.hpp (#include <libprocmon/sdk.hpp> in my case) .

I guess the link error may cause some of your compilation parameters to be different from mine.

like

```cmake
add_definitions(-DUNICODE)
add_definitions(-D_UNICODE)
```

**Comment by unuaunco** [comment]
There is no problem with building and using of example.exe at all.
Only problem is using of static libprocmon.lib library.

> I guess the link error may cause some of your compilation parameters to be different from mine.
> 
> like
> 
> ```cmake
> add_definitions(-DUNICODE)
> add_definitions(-D_UNICODE)
> ```

I'll try to check parameters again, thanks

**Comment by unuaunco** [comment]
Thanks. That works this way

Just for reminder and as example, I left Cmake config that I've used here -> https://github.com/unuaunco/openprocmonlib-static-cmake
