### ISSUE TITLE
请问能否发下成品

### ISSUE THREAD

**Issue by QQ2017** [progmboy/openprocmon#3]
1、请问能否发下成品；
2、请问驱动部分是否逆向的procmon代码得到的，我看功能架构类似

**Comment by progmboy** [comment]
1, 放bin容易让人不放心,自己编译最好(还有就是gui还有好多没完成).
2, 是的,完整逆向procmon驱动(除去了thread performance).
ps:
写这个的时候实际上是用来实现`分支`里的功能的.(抓符号链接漏洞的)

**Comment by QQ2017** [comment]
> 1, 放bin容易让人不放心,自己编译最好(还有就是gui还有好多没完成).
> 2, 是的,完整逆向procmon驱动(除去了thread performance).
> ps:
> 写这个的时候实际上是用来实现`分支`里的功能的.(抓符号链接漏洞的)


再请问下，SDK里面的demo，是否能和原版procmon驱动配套使用呢，比如说 monctl.cxx 中的通讯函数是否能对原版procmon生效？

**Comment by progmboy** [comment]
> > 1, 放bin容易让人不放心,自己编译最好(还有就是gui还有好多没完成).
> > 2, 是的,完整逆向procmon驱动(除去了thread performance).
> > ps:
> > 写这个的时候实际上是用来实现`分支`里的功能的.(抓符号链接漏洞的)
> 
> 再请问下，SDK里面的demo，是否能和原版procmon驱动配套使用呢，比如说 monctl.cxx 中的通讯函数是否能对原版procmon生效？

可以的

**Comment by QQ2017** [comment]
> > > 1, 放bin容易让人不放心,自己编译最好(还有就是gui还有好多没完成).
> > > 2, 是的,完整逆向procmon驱动(除去了thread performance).
> > > ps:
> > > 写这个的时候实际上是用来实现`分支`里的功能的.(抓符号链接漏洞的)
> > 
> > 
> > 再请问下，SDK里面的demo，是否能和原版procmon驱动配套使用呢，比如说 monctl.cxx 中的通讯函数是否能对原版procmon生效？
> 
> 可以的

感谢，测试确实有效！
