### ISSUE TITLE
Registry Path

### ISSUE THREAD

**Issue by mkurkute** [progmboy/openprocmon#5]
Hello, 

Can you please help me to get the registry key path same like file path in CString CFileEvent::GetPath()

I am not sure what structure to be use in case of registry.

Thanks in advance!

-Mak

**Comment by progmboy** [comment]
> Hello,
> 
> Can you please help me to get the registry key path same like file path in CString CFileEvent::GetPath()
> 
> I am not sure what structure to be use in case of registry.
> 
> Thanks in advance!
> 
> -Mak

@mkurkute All of definition of REG struct locate in kernel\logsdk.h

You will see  all of struct start with **KeyNameLength**

That is the REG path length, the path data is following the struct.

for example :

```cpp
CString CRegEvent ::GetPath()
{
	PLOG_ENTRY pEntry = reinterpret_cast<PLOG_ENTRY>(getPreLog().GetBuffer());

	switch (pEntry->NotifyType)
	{
	case NOTIFY_REG_SETVALUEKEY:
	{
		PLOG_REG_SETVALUEKEY pRegSetValueKeyInfo = TO_EVENT_DATA(PLOG_REG_SETVALUEKEY, pEntry);

	        CString strFileName;

	        strFileName.Append((LPCWSTR)(pRegSetValueKeyInfo + 1), pRegSetValueKeyInfo->KeyNameLength);
	        return strFileName;
	}
	break;
        // TODO add more event.
	default:
		break;
	}

	return TEXT("");
}
```

**Comment by mkurkute** [comment]
Thanks for the feedback, code works for me !
