### ISSUE TITLE
More than one include filter.

### ISSUE THREAD

**Issue by mkurkute** [progmboy/openprocmon#6]
Hi,

I want to add more then two include filter but when I add it no data logged. Please see below filters.

	m_Filter.AddFilter(emProcessName, emCMPIs, emRETInclude, TEXT("notepad.exe"));
	m_Filter.AddFilter(emProcessName, emCMPIs, emRETInclude, TEXT("WinMergeU.exe"));

I want to use both filters, can you please help to to fix this issue?

Thanks,
-Mak

**Comment by progmboy** [comment]
@mkurkute 

Hi Mak
I do a commit to fix that.  Please help to verify.
And add support for RegOpt::GetPath()

NOTE:
The implementation of the **UtilConvertRegInternalToNormal** function is relatively simple and may not take into account all the situations, you can modify it according to your own needs

**Comment by mkurkute** [comment]
Hi,
Thanks for the code changes..
I tested new code and filter include (emRETInclude) not working at all, even single filter is not working ..

**Comment by progmboy** [comment]
Okey. try again?

**Comment by mkurkute** [comment]
Yes, Working fine now, Thanks!
