### ISSUE TITLE
How to get child PID

### ISSUE THREAD

**Issue by mkurkute** [progmboy/openprocmon#8]
Hi,

Can you please guild me how can I get the child PID when on process create?

-Mak

**Comment by progmboy** [comment]
Hi,

You mean how to get the new process id when process create?

Use CEventView::GetProcessId()

**Comment by mkurkute** [comment]
Hi,
Main process (p1) creates another child process (p2) , I want get the p2 PID.

**Comment by progmboy** [comment]
I add detail in process create event. You can get what you want.

**Comment by progmboy** [comment]
@mkurkute

**Comment by mkurkute** [comment]
yes, Thanks @progmboy !
I could able to the child PID...
